# Data visualization

En este notebook realizaremos un EDA para poder tener una descripción gráfica de todos los datos proporcionados en el dataset.

In [1]:
import pandas as pd
from pandas.api.types import is_numeric_dtype
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1.Data loading

In [6]:
ruta_site = ("data//SITE.xlsx")
ruta_lab = ("data/LABORATORY_DATA.xlsx")
ruta_hor  = ("data/HORIZON_DATA.xlsx")
ruta_result=("data/suelos_alemania.xlsx")

df_hor = pd.read_excel(ruta_hor)
df_lab = pd.read_excel(ruta_lab)
df_site= pd.read_excel(ruta_site)
df_result = pd.read_excel(ruta_result)

pd.set_option('display.max_columns', None)

In [7]:
df_hor.head(5)

,PointID,HorizontID,Upper limit,Lower limit,Horizon symbol,Soil texture class,Soil colour,Stones,Carbonate class,Organic matter content class,Rooting intensity
0,2,1,0,28,I; Ap,Sl2,7.5YR 3/2,3,C0,h3,Wf4
1,2,2,28,54,I; E,Sl2,10YR 3/3,3,C0,h2,Wf3
2,2,3,54,68,II; Bv,Sl2,7.5YR 4/3,10,C0,h1,Wf3
3,2,4,68,96,III; Bv-ilCv,fSms,7.5YR 6/4,1,C0,h0,Wf2
4,2,5,96,201,III; ilCv,mSfs,10YR 7/4,1,C0,h0,NaN

In [8]:
df_lab.head(5)

,PointID,County,Layer upper limit,Layer lower limit,Horizon lower limit,gS,mS,fS,gU,mU,fU,Sand,Silt,Clay,Soil texture class,pH_H2O,EC_H2O,pH_CaCl2,TC,TOC,TIC,TN,TS,BD_FS,FSS,Water content,Stone density,BD_bulk,Rock fragment fraction,Mn_Ox,Fe_Ox,Al_Ox,Mn_Di,Fe_Di,Al_Di
0,2,SH,0,10,28.0,5.8,33.4,35.4,13.1,3.2,1.5,74.6,17.8,7.6,Sl2,5.29,70.1,4.48,21.83,21.83,0.0,1.79,NaN,1.16,1133.3,20.21,2.65,1.17,2.072453,NaN,NaN,NaN,NaN,NaN,NaN
1,2,SH,10,30,28.0,6.7,32.0,35.8,13.3,3.2,1.6,74.5,18.1,7.4,Sl2,5.11,76.7,4.39,20.75,20.75,0.0,1.73,NaN,1.41,2754.4,19.58,2.65,1.43,2.307925,NaN,NaN,NaN,NaN,NaN,NaN
2,2,SH,30,50,54.0,5.0,27.9,37.8,17.5,3.5,1.7,70.7,22.8,6.5,Sl2,4.63,78.2,3.98,11.51,11.51,0.0,0.82,NaN,1.45,2818.7,15.74,2.65,1.47,2.803774,NaN,NaN,NaN,NaN,NaN,NaN
3,2,SH,50,70,68.0,7.6,31.4,36.6,14.4,3.0,1.2,75.6,18.6,5.8,Sl2,4.73,64.8,4.15,6.91,6.91,0.0,0.49,NaN,1.30,2138.5,11.75,2.65,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN
4,2,SH,70,100,96.0,5.8,43.1,42.3,4.1,1.3,0.6,91.2,6.0,2.8,mSfs,4.90,35.5,4.23,1.57,1.57,0.0,0.11,NaN,1.54,4438.5,5.93,2.65,1.59,3.928302,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_site.head(5)

,PointID,County,Sampling_month,Sampling_year,xcoord,ycoord,Soil_climate_zone,Land use,BZE_peat,Main soil type,Specific soil subtype,Groundwater class,Groundwater level,Thickness of fen or bog,Thickness of peat,Slope,Exposition,Curvature,Type of relief,Position in relief,CS_0_30,CS_30_100
0,2,SH,11,2015,462216.1283,6079359.775,Marsch - Nord,A,0,YE,YE/BB,0,>200,0,0,N0,NaN,GG,V,Z,81.89,54.19
1,3,SH,6,2016,480546.9384,6079739.216,Marsch - Nord,G,0,MD,MDn,GWS4,135,0,0,N0,NaN,GG,TSF,Z,71.62,59.74
2,4,SH,8,2018,484922.3074,6080011.471,Marsch - Nord,A,0,MK,MKn,GWS4,105,0,0,N1,NE,GG,TH,Z,65.60,120.40
3,5,SH,10,2015,497355.9905,6079646.589,Marsch - Nord,G,0,RQ,p2RQ/GG-PP,GWS4,180,0,0,N0.2,SS,GG,KSF,K,88.82,220.87
4,6,SH,10,2015,505020.3377,6080401.370,Geest - Nord,G,0,YU,aGGe-YU,GWS4,140,0,0,N0,NaN,GG,TSF,Z,62.97,84.35

In [12]:
df_result.head(5)

,fid,pointid,bundesland,probenahme_monat,probenahme_jahr,xcoord,ycoord,bodenklimaraum_name,landnutzung,bze_moor,hauptbodentyp,bodenvartypsub,grundwastufe,grundwastand,moormaechtigkeit,torfmaechtigkeit,neigung,exposition,woelbung,reliefformtyp,lageimrelief,kv_0_30,kv_30_100,profile_picture
0,1,35,SH,4,2016,497586.4582,6048053.775,Marsch - Nord,A,0,MC,MCn,GWS4,80,0,0,N0,NaN,GG,TSF,T,72.67,67.87,https://atlas.thuenen.de/webspace/bze_profilbi...
1,2,5319,BW,9,2015,464762.1588,5303762.261,"Schwäbische Alb, Baar",A,0,YK,SS-YK,0,>200,0,0,N2,NE,GG,H,M,148.38,114.00,https://atlas.thuenen.de/webspace/bze_profilbi...
2,3,2,SH,11,2015,462216.1283,6079359.775,Marsch - Nord,A,0,YE,YE/BB,0,>200,0,0,N0,NaN,GG,V,Z,81.89,54.19,https://atlas.thuenen.de/webspace/bze_profilbi...
3,4,3,SH,6,2016,480546.9384,6079739.216,Marsch - Nord,G,0,MD,MDn,GWS4,135,0,0,N0,NaN,GG,TSF,Z,71.62,59.74,https://atlas.thuenen.de/webspace/bze_profilbi...
4,5,4,SH,8,2018,484922.3074,6080011.471,Marsch - Nord,A,0,MK,MKn,GWS4,105,0,0,N1,NE,GG,TH,Z,65.60,120.40,https://atlas.thuenen.de/webspace/bze_profilbi...

In [14]:
df_result['profile_picture'][0]

'https://atlas.thuenen.de/webspace/bze_profilbilder/SH_0035_Z_1.GIF'